<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>

		<OutputType>Exe</OutputType>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<BaseOutputPath>..\Binaries\Physics\</BaseOutputPath>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>..\..\..\docs\Physics\Physics.xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>False</Optimize>
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

</Project>