<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDynamicLoading>false</EnableDynamicLoading>
		<PublishTrimmed>true</PublishTrimmed>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
		<RootNamespace>FastMath</RootNamespace>
		<AssemblyName>FastMath</AssemblyName>
	</PropertyGroup>

</Project>
