<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
		<OutputType>Exe</OutputType>

		<WasmMainJSPath>main.js</WasmMainJSPath>
		<SelfContained>true</SelfContained>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<RootNamespace>Physics.Wasm</RootNamespace>
		<AssemblyName>PhysicsBridge</AssemblyName>

		<BaseOutputPath>..\..\Binaries\Physics\</BaseOutputPath>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>..\..\..\..\docs\Physics\Physics.xml</DocumentationFile>

		<!-- wasm runtime -->
		<WasmEnableThreads>false</WasmEnableThreads>
		<WasmEnableSIMD>true</WasmEnableSIMD>
		<InvariantGlobalization>true</InvariantGlobalization>

		<!-- excessive runtime builds -->
		<EventSourceSupport>false</EventSourceSupport>
		<DebuggerSupport>false</DebuggerSupport>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>

		<!-- comon publishing flags (can be overriden) -->
		<RunAOTCompilation>false</RunAOTCompilation>
		<PublishReadyToRun>true</PublishReadyToRun>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' == 'browser-wasm'">
		<PublishReadyToRun>false</PublishReadyToRun>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<UseSystemResourceKeys>false</UseSystemResourceKeys>
		<Optimize>False</Optimize>
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<IsAotCompatible>True</IsAotCompatible>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<WasmBuildNative>true</WasmBuildNative>
		<WasmEmitSymbolMap>false</WasmEmitSymbolMap>
		<Optimize>True</Optimize>
		<WasmEnableLegacyJsInterop>false</WasmEnableLegacyJsInterop>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vendor\Integration\Integration.csproj" />
	</ItemGroup>
    
    <!-- Compress final WASM build -->
	<Import Project="$(MSBuildThisFileDirectory)GzipCompressWasmAssets.targets" />

</Project>