<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
		<OutputType>Exe</OutputType>

		<WasmMainJSPath>main.js</WasmMainJSPath>
		<SelfContained>true</SelfContained>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<RootNamespace>Physics.Wasm</RootNamespace>
		<AssemblyName>PhysicsBridge</AssemblyName>

		<BaseOutputPath>..\..\Binaries\Physics\</BaseOutputPath>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>..\..\..\..\docs\Physics\Physics.xml</DocumentationFile>

		<!-- wasm runtime -->
		<WasmEnableThreads>false</WasmEnableThreads>
		<WasmEnableSIMD>true</WasmEnableSIMD>
		<InvariantGlobalization>true</InvariantGlobalization>

		<!-- excessive runtime builds -->
		<EventSourceSupport>false</EventSourceSupport>
		<DebuggerSupport>false</DebuggerSupport>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>

		<!-- comon publishing flags (can be overriden) -->
		<RunAOTCompilation>false</RunAOTCompilation>
		<PublishReadyToRun>true</PublishReadyToRun>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' == 'browser-wasm'">
		<PublishReadyToRun>false</PublishReadyToRun>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<UseSystemResourceKeys>false</UseSystemResourceKeys>
		<Optimize>False</Optimize>
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<IsAotCompatible>True</IsAotCompatible>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<WasmBuildNative>true</WasmBuildNative>
		<WasmEmitSymbolMap>false</WasmEmitSymbolMap>
		<Optimize>True</Optimize>
		<WasmEnableLegacyJsInterop>false</WasmEnableLegacyJsInterop>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vendor\Integration\Integration.csproj" />
	</ItemGroup>

	<!-- Build compression for later decompression in browser -->
	<UsingTask
		TaskName="GzipCompressFile"
		TaskFactory="RoslynCodeTaskFactory"
		AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">

		<ParameterGroup>
			<SourceFile
				ParameterType="System.String"
				Required="true" />

			<DestinationFile
				ParameterType="System.String"
				Required="true" />
		</ParameterGroup>

		<Task>
			<Using Namespace="System.IO" />
			<Using Namespace="System.IO.Compression" />

			<Code Type="Fragment" Language="cs">
				<![CDATA[
            using (var input = File.OpenRead(SourceFile))
            using (var output = File.Create(DestinationFile))
            using (var gzip = new GZipStream(output, (CompressionLevel)3))
            {
                input.CopyTo(gzip);
            }

            Log.LogMessage(
                MessageImportance.High,
                $"gzip: {SourceFile} -> {DestinationFile}");
            ]]>
			</Code>
		</Task>
	</UsingTask>

	<Target Name="GzipCompressWasmRuntime" AfterTargets="WasmNestedPublishApp">
		<PropertyGroup>
			<WasmRuntimeFile>$(MSBuildProjectDirectory)\..\..\Binaries\Physics\$(Configuration)\$(TargetFramework)\browser-wasm\AppBundle\_framework\dotnet.native.wasm</WasmRuntimeFile>
		</PropertyGroup>

		<Message Importance="High"
				 Text="WASM runtime: $(WasmRuntimeFile)" />

		<Message Importance="High"
				 Text="WASM runtime exists: $([System.IO.File]::Exists('$(WasmRuntimeFile)'))" />

		<GzipCompressFile
			Condition="Exists('$(WasmRuntimeFile)')"
			SourceFile="$(WasmRuntimeFile)"
			DestinationFile="$(WasmRuntimeFile).gz" />

	</Target>

</Project>
